#!/usr/bin/env node
'use strict'

const Promise = require( 'bluebird' )
const write   = Promise.promisify( require( 'fs' ).writeFile )
const cmd     = require( 'commander' )
const api     = require( './index.js' )

const input = cmd
  .usage( '[packages...]' )
  .description(
    `Determine the latest available version of npm packages `
  + `at a given point in time. `
  + `Parses local package.json if no packages are specified.`
  )
  .option(
    '-d, --date [date]',
    `the date at which the packages should be versioned (defaults to the present moment)`
  )
  .option(
    '-o, --output [filename]',
    `file to write the output to (defaults to stdout)`
  )
  .parse( process.argv )

api( {
  pkgs : input.args,
  date : input.date
} )
  .then( output => {
    if( input.output ){
      process.stdout.write( `Writing output to ` + input.output )
      write( input.output, output )
    }
    else {
      process.stdout.write( output )
    }
  } )
