#!/usr/bin/env node
'use strict'

const cmd = require( 'commander' )
const api = require( './index.js' )

api(
  cmd
    .usage( '[packages...]' )
    .description(
      `Determine the latest available version of npm packages at a given point in time`
    )
    .option( '-d, --date [date]', `the date at which the packages should be versioned (defaults to the present moment)` )
    .parse( process.argv )
)
